# .github/ISSUE_TEMPLATE/bug_report.yml
name: "Bug report"
description: "Create a report to help us improve"
title: "Bug: [describe the bug]"
labels: bug
assignees: 'dheerajoruganty'

body:
  - type: markdown
    attributes:
      value: |
        **Please describe the bug you're encountering in detail.**

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a concise description of the bug."
      placeholder: "What is the bug?"

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Please list the steps to reproduce the bug."
      placeholder: "Step 1, Step 2..."

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "Describe what you expected to happen."
      placeholder: "Expected behavior"

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: "Describe what actually happened."
      placeholder: "Actual behavior"

  - type: textarea
    id: logs
    attributes:
      label: "Relevant logs"
      description: "Include any relevant logs or screenshots that might help us diagnose the problem."
      placeholder: "Paste logs here"
