# .github/ISSUE_TEMPLATE/feature_request.yml
name: "Feature request"
description: "Suggest an idea for this project"
title: "Feature Request: [your idea]"
labels: enhancement
assignees: 'dheerajoruganty'

body:
  - type: markdown
    attributes:
      value: "## Feature Request"

  - type: input
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "What feature would you like to see?"
      placeholder: "Describe the feature in detail."
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "Use case"
      description: "What will you use this feature for?"
      placeholder: "Explain the context in which the feature will be used."
      required: true

  - type: input
    id: benefits
    attributes:
      label: "Benefits"
      description: "How will this feature improve the project?"
      placeholder: "Describe the benefits of this feature."
      required: true
