# .github/ISSUE_TEMPLATE/feature_request.yml
name: "Feature request"
description: "Suggest an idea for this project"
title: "Feature Request: [your idea]"
labels: enhancement
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Please describe the feature you are requesting in detail.**

  - type: textarea
    id: feature
    attributes:
      label: "Feature Description"
      description: "What feature would you like to see?"
      placeholder: "Describe the feature in detail."

  - type: textarea
    id: use_case
    attributes:
      label: "Use case"
      description: "What will you use this feature for?"
      placeholder: "Describe how this feature will be useful."

  - type: textarea
    id: benefits
    attributes:
      label: "Benefits"
      description: "How will this feature improve the project?"
      placeholder: "State the benefits of this feature."
