# .github/ISSUE_TEMPLATE/feature_request.yml
name: "Feature request"
description: "Suggest an idea for this project"
title: "Feature Request: [your idea]"
labels: enhancement
assignees: 'dheerajoruganty'

body:
  - type: markdown
    attributes:
      value: "## Feature Request"

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "What feature would you like to see?"
      placeholder: "Describe the feature in detail."

  - type: textarea
    id: Tasks
    attributes:
      label: "Tasks"
      description: "What tasks to perform"
      placeholder: "Describe the tasks that are needed to be performed"
