name: Python package CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies with Poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry install

      # Step 4: Run tests with pytest
      - name: Run tests
        run: poetry run pytest

  # documentation:
  #   runs-on: ubuntu-latest
  #   needs: test  # Run documentation step only if tests pass

  #   steps:
  #     # Step 1: Check out the repository
  #     - name: Check out code
  #       uses: actions/checkout@v4

  #     # Step 2: Set up Python
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'

  #     # Step 3: Install dependencies with Poetry and build documentation
  #     - name: Build documentation
  #       run: |
  #         python -m pip install --upgrade pip
  #         curl -sSL https://install.python-poetry.org | python3 -
  #         export PATH="$HOME/.local/bin:$PATH"
  #         poetry run sphinx-build -b html docs/source docs/build
