name: Documentation Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Install dependencies and build documentation
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install
          poetry run pip install sphinx  # Explicitly install Sphinx if missing
          poetry run sphinx-build -b html docs/source docs/build  # Build HTML docs in the build folder
